import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Banner from '../components/Banner'
import Navigation from '../components/Navigation'
import ProductCard from '../components/ProductCard'
import Footer from '../components/Footer'
import { GraphQLClient, gql } from 'graphql-request'

const inter = Inter({ subsets: ['latin'] })


const graphcms = new GraphQLClient(
  "https://api-us-east-1.hygraph.com/v2/clbw9x9qu05xj01t1d9pig0oi/master"
);

const QUERY = gql`
  {
    products {
      name
      id
      price
      images {
        url
      }
      slug
    }
  }
  `;

export async function getStaticProps() {
  const { products } = await graphcms.request(QUERY);

  if (data) { }
  return {
    props: {
      products,
    },

    revalidate: 10,
  };
}



export default function Home({ products }) {


  // const products = [
  //   { id: 1, name: "Hoodie", price: 11.99, slug: "hoodie", image: "https://placeholder.com/150" },
  //   { id: 2, name: "Hoodie", price: 13.99, slug: "t-shirt", image: "https://placeholder.com/150" },
  //   { id: 3, name: "Hoodie", price: 16.99, slug: "jeans", image: "https://placeholder.com/150" },
  //   { id: 4, name: "Hoodie", price: 14.99, slug: "hat", image: "https://placeholder.com/150" },
  //   { id: 5, name: "Hoodie", price: 4.99, slug: "sweater", image: "https://placeholder.com/150" },
  //   { id: 6, name: "Hoodie", price: 23.99, slug: "pants", image: "https://placeholder.com/150" },
  //   { id: 7, name: "Hoodie", price: 8.99, slug: "belts", image: "https://placeholder.com/150" },
  //   { id: 8, name: "Hoodie", price: 12.99, slug: "jackets", image: "https://placeholder.com/150" },
  //   { id: 19, name: "Hoodie", price: 26.99, slug: "shoes", image: "https://placeholder.com/150" }
  // ];



  return (
    <>
      <Head>
        <title>Arch</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Navigation />
        <Banner />
        <div className={styles.cardContainer}>
          {products.map((product) => {
            <ProductCard
              key={product.id}
              price={product.price}
              image={product.images.url}
              slug={product.slug}
            />
          })}
        </div>
        <Footer />
      </main>
    </>
  )
}
